version: '3.2'

services:
  russian-cheatsheet-front:
    container_name: russian-cheatsheet-front
    image: psegarra/russian-cheatsheet-front:${VERSION}
    ports:
      - "3034:80"
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '0.1'
        reservations:
          memory: 50M
          cpus: '0.1'